version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Laba3/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=laba3db
      - DB_USER=laba3user
      - DB_PASSWORD=StrongPassword123!
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=laba3db
      - POSTGRES_USER=laba3user
      - POSTGRES_PASSWORD=StrongPassword123!
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laba3user -d laba3db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

